version: 2.0
jobs:
  clonedown:
    docker:
      - image: alpine:3.7
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths:
            - .
  test:
    docker:
      - image: gradle:jdk11
    steps:
      - run:
          name: The First Step
          command: ci/build-app.sh 
      - run:
          name: Do the testing
          command: ci/unit-test-app.sh
      - store_test_results:
          path: app/build/test-results
      - attach_workspace:
          at: .
  build:
    docker:
      - image: gradle:jdk11
    steps:
      - run:
          name: The First Step
          command: ci/build-app.sh 
      - run:
          name: Do the testing
          command: ci/unit-test-app.sh
      - store_artifacts:
          path: app/build/libs
          destination: prefix
      - attach_workspace:
          at: .
workflows:
  version: 2
  two_job_flow:
    jobs:
      - clonedown
      - test:
          requires:
            - clonedown
      - build:
          requires:
            - clonedown
